steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mealmitra:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mealmitra:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mealmitra'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mealmitra:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'

# Tag the image with 'latest' as well
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/mealmitra:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/mealmitra:latest']
  
  # Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mealmitra:latest']

# Store images
images:
  - 'gcr.io/$PROJECT_ID/mealmitra:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mealmitra:latest'

# Substitution variables
substitutions:
  _GEMINI_API_KEY: 'AIzaSyAix7hz00aVUqle2r08-riFh5qbxtyj7dA'  # Default value, will be overridden in the build trigger

# Set a longer timeout for the build
timeout: '1800s' 